
// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.
import { FirebaseOptions, initializeApp, getApps, getApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';

// Fallback configuration with placeholder values
const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  authDomain: "your-project-id.firebaseapp.com",
  projectId: "your-project-id",
  storageBucket: "your-project-id.appspot.com",
  messagingSenderId: "123456789012",
  appId: "1:123456789012:web:XXXXXXXXXXXXXXXXXXXXXX"
};

function initializeFirebase() {
  if (getApps().length) {
    const app = getApp();
    const auth = getAuth(app);
    const firestore = getFirestore(app);
    return { app, auth, firestore };
  } else {
    // Try to parse from environment variable, otherwise use fallback.
    let configToUse = firebaseConfig;
    try {
        const envConfig = JSON.parse(process.env.NEXT_PUBLIC_FIREBASE_CONFIG || '{}');
        if (envConfig.apiKey) {
            configToUse = envConfig;
        }
    } catch (e) {
        // Fallback to placeholder if parsing fails
    }
    const app = initializeApp(configToUse);
    const auth = getAuth(app);
    const firestore = getFirestore(app);
    return { app, auth, firestore };
  }
}

export { initializeFirebase };
